production:
  solr:
    hostname: localhost
    port: 8988
    log_level: WARNING
    max_memory: 128M
    min_memory: 32M

development:
  solr:
    hostname: localhost
    port: 8989
    log_level: INFO
    max_memory: 128M
    min_memory: 32M

test:
  solr:
    hostname: localhost
    port: 8990
    log_level: WARNING
    max_memory: 128M
    min_memory: 32M
